<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RestaurantApp.DataAccess\RestaurantApp.DataAccess.csproj" />
    <ProjectReference Include="..\RestaurantApp.Entity\RestaurantApp.Entity.csproj" />
  </ItemGroup>

</Project>
